map_index:
    path:     /
    defaults: { _controller: "MapBundle:Map:index" }
    methods:  GET

map_show:
    path:     /{id}/show
    defaults: { _controller: "MapBundle:Map:show" }
    methods:  GET

map_new:
    path:     /new
    defaults: { _controller: "MapBundle:Map:new" }
    methods:  [GET, POST]

map_edit:
    path:     /{id}/edit
    defaults: { _controller: "MapBundle:Map:edit" }
    methods:  [GET, POST]

map_delete:
    path:     /{id}/delete
    defaults: { _controller: "MapBundle:Map:delete" }
    methods:  DELETE
